name: APR

dataset:
  data_dir: Data/yelp
  tr_neg : 1
  val_neg : 99
  tr_bs :  256
  val_bs :  128
  # num_workers : 4

model_config:
  # embed_size: 64
  top_k: 10
  reg : 0.01
  eps : 0.5
  reg_adv : 1.0

  optimizer :
      lr : 0.003 
      betas : [0.9, 0.999] 
      weight_decay : 1e-2 
      eps : 1e-9  

training:
  max_epochs: 25
  accelerator: cpu
  log_every_n_steps: 20
  reload_dataloaders_every_n_epochs: 1
