name: BPR

dataset:
  data_dir: Data/yelp
  tr_neg : 1
  val_neg : 127
  tr_bs :  256
  val_bs :  256
  # num_workers : 4

model_config:
  embed_size: 64
  top_k: 10
  reg : 0.01
  eps : 0
  reg_adv : 0

  optimizer :
      lr : 0.01 
      betas : [0.9, 0.999] 
      weight_decay : 1e-2 
      eps : 1e-9  

  scheduler :
      T_0 : 2000 
      T_mult : 2 
      eta_min : 0.001

training:
  max_epochs: 50
  # fast_dev_run: 16
  accelerator: cpu
  log_every_n_steps: 20
  reload_dataloaders_every_n_epochs: 1
